- name: instalar wordpress
  shell:
    cmd: wget https://es.wordpress.org/latest-es_ES.tar.gz

- name: descomprimir wordpress
  shell:
    cmd: tar -xvzf latest-es_ES.tar.gz

- name: mover wordpress a documentroot
  shell:
    cmd: mv wordpress/* /var/www/html

- name: cambiar propietario de documentroot
  shell:
    cmd: chown -R www-data:www-data /var/www/html
  notify:
  - restart apache2
